"""Adding longitude and latitude to Pitch model

Revision ID: 17d80e9768af
Revises: 30381dc7c9fe
Create Date: 2024-12-30 15:43:01.877428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d80e9768af'
down_revision: Union[str, None] = '30381dc7c9fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('pitch', sa.Column('longitude', sa.Float(), nullable=True))

    # Update existing rows with default values
    op.execute('UPDATE pitch SET latitude = 0 WHERE latitude IS NULL')
    op.execute('UPDATE pitch SET longitude = 0 WHERE longitude IS NULL')

    # Alter columns to be non-nullable
    op.alter_column('pitch', 'latitude', nullable=False, type_=sa.Float())
    op.alter_column('pitch', 'longitude', nullable=False, type_=sa.Float())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'longitude')
    op.drop_column('pitch', 'latitude')
    # ### end Alembic commands ###
