"""Change Status for reservation

Revision ID: 30381dc7c9fe
Revises: 3518127fdcd7
Create Date: 2024-11-17 20:53:45.887259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30381dc7c9fe'
down_revision: Union[str, None] = '3518127fdcd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation', 'status',
               existing_type=sa.VARCHAR(length=8, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Enum('PENDING', 'CONFIRMED', 'CANCELED', name='status'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation', 'status',
               existing_type=sa.Enum('PENDING', 'CONFIRMED', 'CANCELED', name='status'),
               type_=sa.VARCHAR(length=8, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    # ### end Alembic commands ###
