"""Add price to Pitch

Revision ID: d0ba3e5521a9
Revises: a2169ed7ad29
Create Date: 2024-11-16 20:08:06.732716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0ba3e5521a9'
down_revision: Union[str, None] = 'a2169ed7ad29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'price')
    # ### end Alembic commands ###
